# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 837042b725f4dff8123739c193e3f904efcb66d25fcdc2e361a0f050d88ad039e59ba7c8a2a160e1beeb3169ee31966641a27310123e14a2067c96b37939ae50

test:
  secret_key_base: a68b469bebe068303ca11762f7e7f0a53b24c6322fab00a7a71db2d0ff786c3d4680332f6b8e8e5669d8e8780dabd5904ccb6a396bc5ed24763fea73e845551a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
